### ISSUE TITLE
Have you tried yubikey-touch-detector?

### ISSUE THREAD

**Issue by Kranzes** [lheckemann/ssh-agent-notifier#1]
yubikey-touch-detector with --libnotify seems to do what you want, except it supports more than just ssh.

**Comment by lheckemann** [comment]
(linking for convenience: https://github.com/maximbaz/yubikey-touch-detector )

Thanks! That does look like it would have solved my problem as well. I do like being notified when my non-yubikey SSH keys are used as well though (and I have some further Crimes planned involving custom SSH agents), so I'll probably still use this.
